### ISSUE TITLE
Missing hobo data for DHHL

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#13] opened 2017-10-09 20:35 UTC
hobos with sensor_sn 9796070 and 9796074 are missing from the database although the hobo files had been placed in the /var/local/scrape-util/dhhl-hobo-u12/input folder and appear in the archive folder. One of the 9706070 files appears in the errors folder on this filepath.

In the view "dates_readings" in dhhl database, if you search for these sensor_sn, the dates are null, so no data for them.  I'll upload screenshots.
![missing hobo data](https://user-images.githubusercontent.com/29083044/31357475-9aac1b8e-acdd-11e7-8426-4dd8ffa62259.PNG)
![missing hobo data 2](https://user-images.githubusercontent.com/29083044/31357478-9de9b5e0-acdd-11e7-9977-3d29e493c577.PNG)

**Comment by carlosparadis** [comment] 2017-10-11 21:27
I see the files on the server, and there is an unfinished notebook on HOBO Reshaping we could use as a starting point: https://github.com/erdl/sensors/blob/master/hobo/hobo_notebook.ipynb

We can try starting from there. I have no idea why the file was moved to the `error` folder, however. It loads fine in R so it is not a bad format issue. Maybe there are duplicates in the .csv and readings table?

**Comment by eileenpeppard** [comment] 2017-10-11 21:48
I don't know.

**Comment by jygh98** [comment] 2017-10-13 23:47
Strange, the 9796070.csv formats fine when I run it using the 12 python script.  Would you want to send you the formatted csv for it so you can upload it the database?  Also there are more error files that pop up in the error folders from a few days ago.


![image](https://user-images.githubusercontent.com/25787662/31570187-0674803a-b01d-11e7-9f5e-0d4037ebbf39.png)

**Comment by carlosparadis** [comment] 2017-10-14 02:34
@jygh98 Do we have any error message in that errorlog you told me about today associated to these files?

**Comment by jygh98** [comment] 2017-10-16 21:58
Yes so for anytime during the export and scrape-util has an error uploading a row to the database, the script will make a csv file for these rows that are not able to be uploaded as seen above.  

At the same time the script will create a log of all the corresponding errors in here

![image](https://user-images.githubusercontent.com/25787662/31637145-0b1abdea-b269-11e7-8f25-dd4307e5e01f.png)

Opening the file you will see this

![image](https://user-images.githubusercontent.com/25787662/31637162-1dfb654a-b269-11e7-98dd-035ec1c77781.png)

If you convert the timestamps from the error log to UTC -10 to the csv upload time you will see the times do indeed match.

**Comment by carlosparadis** [comment] 2017-10-16 22:18
@jygh98 OK so we know the error log is matching, but you didn't follow up on the actual problem. What is this byte `0xb0` and `0xf8` that the log is reporting for the file? Is this some garbage from Excel or the .csv file generated by the HOBO scrape-utils is not being able to parse? 

Do not modify the original reported file, we want to have a sample of the problematic file to check if this is a problem on how the csv is exported from the HOBO afterward.

**Comment by jygh98** [comment] 2017-10-16 23:00
So here is the range 0x80 - 0xBF for UTF-8 encoding

0x00 - 0x7F - Single byte sequence, backwards compatible with ASCII 
0x80 - 0xBF - Continuation byte for multi byte sequences 
0xC0 - 0xDF - Starter byte for two byte sequence 
0xE0 - 0xEF - Starter byte for three byte sequence 
0xF0 - 0xF7 - Starter byte for four byte sequence 
0xF8 - 0xFB - Starter byte for five byte sequence (overlong encoding) 
0xFC - 0xFD - Starter byte for six byte sequence (overlong encoding) 
0xFE - 0xFF - Illegal bytes

The main error of "utf-8" codec cant decode is that a character cant be read.  I have class in a bit and will update this post later.
--

**Comment by carlosparadis** [comment] 2017-10-16 23:02
Yes, I know what a UTF-8 encoding is. We need to find out what is it in the file by opening as a .txt. And OK keep us posted here, thanks!

**Comment by jygh98** [comment] 2017-10-18 23:06
Updated the comment with a tldr

**Comment by carlosparadis** [comment] 2017-10-18 23:13
@jygh98 Nice data Sherlocking post @jygh98. So basically the weird exports 

- 1) had their second units missing
- 2) had the degree symbol being reported on the unit.

I guess the ball is now on @eileenpeppard to figure out if she exported anything differently. 

For testing purposes, could you attach me the first 10 lines of the problematic file and 10 lines of an ok file? I want to create a few unit tests and also do a test run on the HOBO notebook that takes as input this format.

@eileenpeppard , what is your take on this question about:

> As to why only some hobos upload their data with different symbols that are not utf-8 compatible, I am not too sure. Possibly we are not exporting the same settings?

**Comment by jygh98** [comment] 2017-10-18 23:28
Here is the files with each csv: [csv.zip](https://github.com/erdl/legacy-scrape-util/files/1396614/csv.zip)
The archived label is a compatible csv, while the error is the error csv

**Comment by jygh98** [comment] 2017-10-26 02:43
@eileenpeppard 
We discussed it today and believe the issue is due to how the csv's were save considering the different formats.

**Comment by eileenpeppard** [comment] 2017-11-01 01:08
![2017-10-06 dhhl missing hobo files](https://user-images.githubusercontent.com/29083044/32255606-52d0d5a8-be4d-11e7-8d8d-c0c4483b0f2c.PNG)

**Comment by carlosparadis** [comment] 2017-11-01 01:09
@eileenpeppard Last conclusion was that the format the files are being saved is different than before. Are you saving anything different or updated the software for the hobo?

**Comment by eileenpeppard** [comment] 2017-11-01 02:19
![difference in hobo files](https://user-images.githubusercontent.com/29083044/32257082-f52bcd7c-be56-11e7-9042-0bfcfc7394ca.PNG)
file for 9796095 failed to upload and had different time format and different quotes - are these important to scrape-util? Strange since I used the same software. i'll see if i can find the hoboware files and re-export the data.

**Comment by eileenpeppard** [comment] 2017-11-01 02:36
okay, so i've re-extracted the data from the hobo files and they look better, so i put them in the input folder for scrape-util to take another crack at uploading them! I'd named the hobos inconsisitantly and i think as i had originally fiddled with the files i must have used Excel and it changed the format.  So i've manually changed the name of file and name in first line. 
![corrections](https://user-images.githubusercontent.com/29083044/32257530-aa4918ac-be59-11e7-906f-6bdbb6aeb5b9.PNG)

**Comment by eileenpeppard** [comment] 2017-11-01 19:00
Okay, this issue is resolved. The data loaded.

**Comment by carlosparadis** [comment] 2017-11-01 20:39
Thanks, I am closing it.

**Closed by carlosparadis** 2017-11-01 20:39 UTC
Labels: prio: high, stat:next, type: missing data

**Comment by carlosparadis** [comment] 2018-01-03 01:57
Details of this issue are now being recycled into wiki documentation on the sensors project by @kathrynparadis. See [this issue](https://github.com/erdl/legacy-scrape-util/issues/13) for more details.
