### ISSUE TITLE
Verify what are the non-versioned files on the server 

### ISSUE THREAD

**Issue by carlosparadis** [erdl/legacy-scrape-util#10] opened 2017-09-21 12:20 UTC
There is a number of files who are not versioned in the server's scrape-util folder since Forrest left. This is undesirable, as we would like to keep the server always in sync with GitHub. This would ensure we can always revert back and forth if something that is changed is broken, and also easily identify what was modified rather than keep text files like today.

The current list of modified files was as noted by Eileen were the following: 

```
'e785' = 785, 'e786' = 786, 'e795' = 795, 'e792' = 792

'e785-Whole-house' = 187
'e785-Water-heater' = 188
e785-ACC = 189
e785-AHU = 190
e785-Dryer = 191
e785-Range = 192
'e785-Kitchen-refrigerator' = 193
e785-Other = 194

e786-PV	= 195

'e795-Whole-house' = 196
'e795-Water-heater' = 197
e795-ACC = 198
e795-AHU = 199
e795-Dryer = 200
e795-Range = 201
'e795-Kitchen-refrigerator' = 202
e795-Other = 203

e792-PV	= 204
```

Navigate to the server to:

```
/var/local/scrape-util/projects
```

And compare the changed files to the ones currently in this project's Github. Also, take note that the project on the server has a dozen folders that I am unsure how much it is in sync with Forrest's Github or are being ignored. @ryantanaka may be able to help you with doing this sort of comparison, as he had to do for `survey_display`.

Do also note that I didn't sync up to this point the remote from fspmarshall to this one. I.e. `git remote --v` will not show this repo.

p.s.: Could you also write here the syntax you mentioned on using or not the quotes?

**Comment by carlosviansi** [comment] 2017-09-21 12:28
Note: Priority was set to high as we don't want to keep adding sensors without syncing them to this project.

**Comment by ryantanaka** [comment] 2017-11-23 02:45
Notes from Nov 22 conf call:

The two files: 

`/var/local/csbcd-configs/scrape-util-projects/dhhl/config.toml`
`/usr/local/lib/scrape-util/tmp/projects/dhhl/config.toml`

Appear to be exact copies of each other such that when one is edited, the other is automatically edited as well. We are unsure how these two are linked and it needs to be investigated.

Also, we need to find out when Eileen needs to add new sensors to scrape-util so that we have a deadline for figuring this versioning problem out.

**Comment by carlosparadis** [comment] 2017-11-23 08:29
This one earned this tag as well. There is one more `wtf` tag on the `survey_admin` project insofar. Jokes aside, we want to make sure we have a collection of issues to make sure newcomers avoid doing at all costs and see on the long-term how much that these things can sink.

**Comment by ryantanaka** [comment] 2017-11-25 00:08
@jygh98 @carlosparadis 

In regards to my comment above:

> The two files:
`/var/local/csbcd-configs/scrape-util-projects/dhhl/config.toml`
`/usr/local/lib/scrape-util/tmp/projects/dhhl/config.toml`

These two files are hard links to the same location on disk. Watch this short [video](https://www.youtube.com/watch?v=lW_V8oFxQgA) for a quick intro. 

Running the command `ls -i` on both files reveals that they have the same inode number, and are therefore hard links. If we edit one "file", the change appears in the other "file". If we delete one, the other remains and data on disk is not wiped until all hard links pointing to that inode number are deleted according to this [Stackexchnage post](https://superuser.com/questions/12972/how-can-you-see-the-actual-hard-link-by-ls/12973#12973). See also this [Wikipedia post](https://en.wikipedia.org/wiki/Inode) for more info on inode. 

Let me illustrate that these two files are hardlinks to the same location on disk:
```
ryan@csbcd01:/usr/local/lib/scrape-util/tmp/projects/dhhl$ ls -i /var/local/csbcd-configs/scrape-util-projects/dhhl/config.toml
128588839 /var/local/csbcd-configs/scrape-util-projects/dhhl/config.toml
ryan@csbcd01:/usr/local/lib/scrape-util/tmp/projects/dhhl$ ls -i config.toml
128588839 config.toml
```
Both files have the inode# 128588839.

This scrape-util project also contains soft links as we've seen. 

With that said, we need to know:
- What points to what?
- Which file does scrape-util actually refer to if there is more than one file corresponding to some data on disk?

**Comment by carlosparadis** [comment] 2017-11-25 04:42
@ryantanaka When we discussed this in the lab, I mentioned symbolic links could be soft or hard. So, this is the hard variant. Maybe `ls -l` only shows the `->` symbol only for the soft variant. 

- I think you missed the main question: To what purpose was this done? 

Can you remind me again if both folders had the source code for scrape-utils?

**Comment by ryantanaka** [comment] 2017-11-25 05:34
So I didn’t address that question yet, I have no idea. I just wanted to shed some light on that one specific case so we all have an idea of how it works. 


I’ll get back to you on the second question.

**Comment by ryantanaka** [comment] 2017-11-28 22:05
## Notes on Scrape-Util & 11/27 conference call recap
![scrape_util_mess](https://user-images.githubusercontent.com/19616012/33345378-459bda88-d430-11e7-9ce8-0f77eebb08aa.jpg)

Above is an image of `scrape-util` as it's laid out in our server. The red text are descriptions of conventional linux file system usage, which would help to explain why things were split up the way they were. The right hand side of the image (blue box) represents the `/usr` folder where scrape-util source code resides. The left hand side of the image represents the `/var` folder where scrape-util's config files, error logs, raw files, etc. are stored. Arrows going over illustrate the symbolic links. I know i mentioned `hard links` in my previous comment but I think I may have been mistaken as the `pwd` command shows paths based on where you navigated from. In other words, navigating through a symbolically linked directory, then entering `pwd` immediately after does not show the absolute path to the directory you are currently at, but rather the path made through the link. 

The usage of `/tmp/` is specified in the README [here](https://github.com/erdl/legacy-scrape-util/tree/master/tmp). 

As for the versioning of the files, it appears that the scrape-util source code is up to date with our remote repo here on the ERDL page (see the commit logs). As for the contents of `csbcd-configs`, they are not versioned on our ERDL github. In fact Forrest had them on a completely different repo (do a `git remote --v` to see this) so a local git repo is there. 

@jygh98, can you take a look at the files on the left hand side of the image and take note of what **needs** to be versioned versus what can be ignored (e.g. error logs)? Once we know that, then we can version what we need. Also I'm not sure if any of those files contain sensitive information such as passwords so be sure to take note of that too so we don't accidentally put it up on github. Let me know too if see any discrepancies with the above diagram since you've been looking at the program more than me. 

I'll be working on putting together a diagram like the one above to illustrate the setup better for us so we all have a good understanding of how the program is laid out in the server (especially with all this symbolic linking).

@carlosparadis, anything else you'd like to add?

**Comment by jygh98** [comment] 2017-11-30 01:04
So here is the full list of unstaged files in `csbcd-configs`
![image](https://user-images.githubusercontent.com/25787662/33406926-2ab6d81a-d513-11e7-8fde-41007530fd93.png)


With all these files the permissions were changed from `100644` to `100755`
![image](https://user-images.githubusercontent.com/25787662/33407263-9f577282-d514-11e7-912e-f098b36625ae.png)
![image](https://user-images.githubusercontent.com/25787662/33407273-ac3f0f28-d514-11e7-9ecf-d30890807bf1.png)
![image](https://user-images.githubusercontent.com/25787662/33407275-b068cb98-d514-11e7-84f5-f0b0a0b4316a.png)


In `/scrape-util-projects/dhhl/config.toml`, new egauges were added but also the word 'refrigerator' was adjusted from 'refridgerator'.  This was due to the spelling was different from how it was specified on egaurd and Eileen ended up noticing something was off when we were only missing refrigerator data.
![image](https://user-images.githubusercontent.com/25787662/33407399-4b268026-d515-11e7-986f-7f3e7f33492b.png)

Final change was in `/scrape-util-projects/occupant-query/config.toml` in which a single change was made
![image](https://user-images.githubusercontent.com/25787662/33407698-a012da16-d516-11e7-9dd4-381796906090.png)

**Comment by ryantanaka** [comment] 2017-12-16 00:18
@jygh98, thanks for looking into this. @carlosparadis and I looked over your findings and will proceed to get started on versioning this. 

12/15 Conf Call Notes:

There are three commits that I will make to this repository:
- 1 for all the file that had its mode has changed
- 1 for dhhl/config.toml where new sensors were added
- 1 for another file (we discussed this one) I will also be sending out an email regarding the contents of this one file.

**Comment by ryantanaka** [comment] 2017-12-16 00:36
It looks like this "mode change" thing is a result of however Forrest set this up. It cold have happened when he pulled things from his repo. TBH I just realized we probably could have changed the permissions back to what it was, but I wouldn't want to risk breaking anything. 

https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

**Comment by ryantanaka** [comment] 2017-12-27 01:30
12/22 conf. call notes

- Eileen followed up with Justin to see what he has to say about the last commit that we need to do
    - still waiting to here back, ball is in his court atm

**Comment by ryantanaka** [comment] 2018-01-12 01:42
1/10/18 meeting w/Justin & @carlosparadis notes

- What we covered:
     - expressed our concerns of the last commit
     - tried to run scrape-util as a different user, however it failed and we reverted it back to how it was running prior
        - this issue seems to stem from the fact that scrape util needs permission to access certain files and directories (we need to know all of them)

- What we didn't cover yet:
    - `user` table [issue](https://github.com/erdl/survey_display/issues/15)
    - checking on failed logins into the server

Justin and I will meet again sometime next week (waiting to hear back from him) to go over the issues.

**Comment by ryantanaka** [comment] 2018-01-25 22:19
Justin confirmed that it is okay for us to do the final commit mentioned above. I've done the commit as well as added `scrape-util-projects/occupant-query/raw` to the `.gitignore` because that folder was specified in the config to hold raw occupant query files.

**Comment by ryantanaka** [comment] 2018-03-06 00:38
[csbcd-configs.zip](https://github.com/erdl/legacy-scrape-util/files/1783114/csbcd-configs.zip)

Storing this here for the time being. These configs are current up to 3/5/18 2:35pm

**Comment by ryantanaka** [comment] 2018-05-12 01:06
Versioned and non versioned config files have been verified. Additionally they are backed up and we currently have a repo to store them located [here](https://github.com/erdl/scrape_util_configs). Closing this issue.

**Closed by ryantanaka** 2018-05-12 01:06 UTC
Labels: prio: high, stat:next, type: settings, wtf?
