### ISSUE TITLE
New Window Sensors to add to Scrap-util

### ISSUE THREAD

**Issue by kathrynparadis** [erdl/legacy-scrape-util#30] opened 2019-05-10 01:17 UTC
Insert new window sensors into the scrap-util:

Frog 1 (purpose_id 118):
ABSPATH:1:#frog1_duct_sensors_1/window_open_tr

Frog 2 (purpose_id 119):
ABSPATH:1:#frog2_duct_sensors/window_open_tr

**Comment by kathrynparadis** [comment] 2019-05-10 01:32
@carlosparadis

**Comment by carlosparadis** [comment] 2019-05-13 09:00
I just updated the files, so sensor data should be coming in. @eileenpeppard Please confirm. 

Sensors were added per the notes I've done for the previous sensors at: https://github.com/erdl/scrape_util_configs/wiki

@ryantanaka I don't know why we have a csbcd-configs folder and another one for the actual configs being used by the tool. Any idea? As it stands, both are versioned, and pointing to this repository. I intended to maintain the pipeline of sending configs to Github, and then pulling from the server, but adding a sensor requires editing a file that is tracked (value-remap.toml) and one that is ignored (webctrl-config.toml), which is even more confusing. So I edited directly in the server. 

I am assuming we had to leave webctrl-config.toml out due to sensitive information being mixed in?

**Comment by carlosparadis** [comment] 2019-05-14 06:33
I verified the data is not coming in. And I believe I found the problem:

<img width="554" alt="Screenshot 2019-05-13 20 31 30" src="https://user-images.githubusercontent.com/17270563/57675609-28304980-75be-11e9-8b2a-375e52d85171.png">

@eileenpeppard The readings table reading column expects a double, but we are receiving TRUE or FALSE from Webctrl. This needs to be changed at the source to be numeric.

**Comment by carlosparadis** [comment] 2019-05-14 20:06
From Eileen today: 

> I’m passing on the request to change to 0 or 1 and also give status every 5 minutes.

**Comment by ryantanaka** [comment] 2019-05-15 00:05
@carlosparadis, you are correct, we left out anything with sensitive information and versioned everything else. If one of the files you had to change was not versioned for that reason, I would have done the same and updated it directly in the server too.

**Comment by eileenpeppard** [comment] 2019-05-15 00:37
Jason Forrester of Island Controls did fix it for us - I confirmed it is now giving a 0 or 1 every five minutes.  It looks like he kept the same names:
ABSPATH:1:#frog1_duct_sensors_1/window_open_tr
ABSPATH:1:#frog2_duct_sensors/window_open_tr

Here was his email: 
Okay so I made it every 5 minutes, *however* there's not any way that I'm aware of to make the 'digital' trend point numeric.
What I *can* do is change the value to a number in the program, and store as a numeric trend.
That's probably going to mess up your export but I'll try to make the names the same.

**Comment by carlosparadis** [comment] 2019-05-15 00:41
@eileenpeppard I'm not sure I understand what he said there: 

So I think what he is saying is, he will receive the data as-is in webctrl, and **inside webctrl** transform it into 0 and 1 before **storing in webctrl**. Is this correct?  

If the names needs be changed I can modify it easily. What is important is that **all data sitting in webctrl under this ABSPATH is consistently 0 and 1**. 

I have not been able to access webctrl website for a while, and @kathrynparadis has issues too which makes sanity checking hard on my end most of the time. 

Could you confirm all data is 0 and 1 and still in the same ABSPATH?

**Comment by carlosparadis** [comment] 2019-05-15 00:43
@ryantanaka Can you confirm, for the sake of upfront potential need, if Forrest ever identified a portion of his code to do this kind of transformation before storing the data? Did you ever spot such a thing?

**Comment by eileenpeppard** [comment] 2019-05-15 01:24
Carlos, I've checked the data and it looks trying to attach screenshot.
 [good.[](url)](url
![window data](https://user-images.githubusercontent.com/29083044/57742275-3339b700-765c-11e9-9e16-cec17b3e2556.JPG)
)

**Comment by eileenpeppard** [comment] 2019-05-15 01:25
You should not have to transform data, it's good to go. Jason managed it on Webctrl.

**Comment by kathrynparadis** [comment] 2019-05-15 02:04
Just to keep track of this:

On WebCtrl, Jason deleted the old sensor (the one that had True/False data from 2019-04-16), and recreated it as the same sensor name, but with a new data type (0's and 1's). So the data from before today (2019-05-04) is completely gone.

**Comment by eileenpeppard** [comment] 2019-05-15 02:15
Yes, exactly!  I guess he couldn't mix data types either.

**Comment by carlosparadis** [comment] 2019-05-15 03:05
@eileenpeppard the data has been added to scrape-util and is now in the database. Found a couple more issues with this scrap that I need to add here in the interest of saving the next poor soul adding sensors a few lifetime hours.

**Comment by carlosparadis** [comment] 2019-05-15 03:10
@ryantanaka please follow-up on confirming me what I asked on scrape-utils having any separate code file that allows for transformations based on what I read in the code, in case we come to need this in the future when you're no longer around. I will close the issue after I hear back from you.

**Comment by ryantanaka** [comment] 2019-05-27 05:33
@carlosparadis, from what I can see we are not transforming any of the values that end up in the `reading` column of the `reading` table. 

Based on `field-remap.toml` and `value-remap.toml` in `/usr/local/lib/scrape-util/tmp/projects/uhm-frog`the only conversion that I can see is making timestamps into ints (see line 11 of value-remap.toml).

**Comment by carlosparadis** [comment] 2019-05-27 20:25
@ryantanaka thanks! I had some faint memory it was somewhere. Closing this issue!

**Closed as completed by carlosparadis** 2019-05-27 20:25 UTC
Labels: prio: high, type: new sensors
