### ISSUE TITLE
Missing webctrl data for uhm frogs

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#14] opened 2017-10-10 20:20 UTC
Some data is missing between 2017-05-11 15:00 and 2017-05-31 08:00.  Can this be harvested somehow? Even manually and i'll upload it to a staging table to move it into the reading table.  I believe the data missing in April is not in the webctrl database - the internet was down for an entire long weekend and data lost.
![missing webctrl data](https://user-images.githubusercontent.com/29083044/31408540-a8351d60-ada4-11e7-8f3b-15167b8ddb00.PNG)

**Comment by carlosparadis** [comment] 2017-10-10 20:37
What are the sensor ids? This is frog uhm right?

**Comment by eileenpeppard** [comment] 2017-10-10 21:06
Yes, frog uhm and I'm not sorting through each sensor. Best to try to get all data for that time period. Thanks.

**Comment by carlosparadis** [comment] 2017-10-11 02:24
It is much easier if you just pinpoint the sensors we need so we only request and re-insert what is needed. I don't have the notebooks ready yet, so I guess it is best you check with Jason on this.

**Comment by eileenpeppard** [comment] 2017-10-11 02:38
No, Carlos, I am not sorting through over 100 sensors. Just get everything in that time slot, send to me and i'll sort it out myself.

**Comment by carlosparadis** [comment] 2017-10-11 02:39
@jygh98 you hear her. I will be sleeping for 5 hours to then get a 15 hours flight, so I won't be able to get to this anytime soon. Good luck!

**Comment by kathrynparadis** [comment] 2017-10-11 07:54
Wasn't this the data we were looking into back at the beginning of August? I think I manually checked for the sensors that had data at that time, and wrote them down in a notepad somewhere on the laptop you lent me, Eileen. Did we never get around to filling in the missing data? The data in April is definitely not on Webcntrl, and the data from May 11-30th definitely is. I remember that much. 

I could get that information and get it to Jason fairly easily, it would just take a bit of time, but I won't be in the office again until Friday, do you need it sooner than that? (Also, if there's something like this that would be time consuming for you to do Eileen, I could always work on it for you if you don't have the time.)

**Comment by eileenpeppard** [comment] 2017-10-11 18:59
It is not worth the hassle for Jason to pick and choose sensors in a script. He should just get the whole time period I mentioned, give me the data and I'll load it to a temporary table and get sql to fill in the missing readings in the reading table. The next step is to get a script that can go over the time period and get the data, insert it without getting an error for trying to put a duplicate in.

**Comment by carlosparadis** [comment] 2017-10-11 19:38
@eileenpeppard no problem, he can just get all the data with the 12 python notebook he has, and how he got your last bunch of files. 

> It is not worth the hassle for Jason to pick and choose sensors in a script. He should just get the whole time period I mentioned

Maybe this is true for webctrl, but I don't know if this approach will work for egauges, because they are not always available like wtbctrl. If we don't know which sensors are the ones missing data, we will just keep re-running the scripts blindly "until it works". 
 
We can just try to code something that once ran spits out a sensor id and a sequence of time windows where data is missing. We should also be able to understand why data is missing. Stacking up band-aid solutions will not scale-up. 

Do you know why we have a hole this time on this time window? Was it another case of sensor added to scrape-utils after it was installed?

**Comment by eileenpeppard** [comment] 2017-10-11 20:28
The holes are there for some mysterious reason - it took Forrest a while to get his scripts to work and i had not gotten him to rerun them over that time period to fill in the gap. Too many things going on at the time.

**Comment by carlosparadis** [comment] 2017-10-11 20:31
I see, I guess given the time range it is safe to say it is not a bug in the current code as is, just "legacy holes" in the data. We are still lacking on the visualization side to see all of them given they keep reappearing like the plague.

**Comment by eileenpeppard** [comment] 2017-10-11 20:58
Lagacy holes. No, they are not 'reappearing', just never addressed. the current code is working fine.

**Comment by eileenpeppard** [comment] 2017-10-12 22:30
Okay, the data that Jason gave me had problems uploading to the database. Even though it was csv, and when I looked at it with Notepad++, it looked fine. Got error when I uploaded from command line. when i opened file with plain notepad i could see there were no line breaks. Weird! I had to open file with Excel and re-save it to get the line breaks and upload it.
![problem with webctrl data output format](https://user-images.githubusercontent.com/29083044/31522369-2acd8a82-af49-11e7-95f5-16a6ef757a00.PNG)

**Comment by carlosparadis** [comment] 2017-10-12 22:35
Thank you for letting me know about the problem with the csv.

@eileenpeppard Does this means you got all your need associated to this particular issue of missing data?

@jygh98 What did you run to get this? My WebCTRL Notebook or the 12 python notebook script on #6 ? I would like to know if it is the current notebook to fix it.  WebCTRL data is exported as a `JSON` file rather than a csv. Maybe the code is not properly reformatting the data when saving it.

**Comment by eileenpeppard** [comment] 2017-10-13 00:44
Hi, Guys.
Okay, I think we have all the webctrl data we are able to get.  There is data missing from the actual webctrl database between May 17 10am and May 23 9am. it's just not there.  A side note: Jason's data scrape yesterday got the eGauges too, not just webctrl.  thanks for the hard work. I'll let you know when we're missing other data. i see a drop in Oct data but urgent.
![missing may webctrl](https://user-images.githubusercontent.com/29083044/31525189-230635fe-af5a-11e7-8490-6248d0039156.PNG)

**Comment by jygh98** [comment] 2017-10-13 00:49
Interesting, I go ahead and check on why it is formatted like that.  Also @carlosparadis this was using the 12 python file, I think its just formatting issue during the datetime conversion.

**Comment by eileenpeppard** [comment] 2017-10-13 00:52
okay here is where we are missing in October and I think the data is all there in webctrl: all sensors from
2017-10-07 06:00 to 2017-10-07 08:00 and 2017-10-08 03:00 to 2017-10-08 05:00

**Comment by carlosparadis** [comment] 2017-10-13 01:26
@eileenpeppard This `Oct` request is a way more recent date. Was this because it was added afterward or is it a script issue? 

@jygh98 I wouldn't waste time on this, the plan is we move to the individual notebooks by the start of the next week, so you would be trying to pinpoint a problem on a code we won't use very soon. A saveas on Notepad++ sounds easy enough to do for just the week than the time trying to locate and fix the code. Additionally, you may end up breaking other parts of it that assume this "issue".

**Comment by jygh98** [comment] 2017-10-13 22:56
Okay @eileenpeppard I sent you the two csv through file drop, let me know if the csv is still giving you trouble.  I double checked with opening it in notepad and notepad++ and it seems fine.

**Comment by carlosparadis** [comment] 2017-10-16 22:10
@kathrynparadis @jygh98 For the record, I spoke with Eileen now -- There were two requests in this issue by her:

## First Request

> Some data is missing between 2017-05-11 15:00 and 2017-05-31 08:00. Can this be harvested somehow? Even manually and I'll upload it to a staging table to move it into the reading table. I believe the data missing in April is not in the webctrl database - the internet was down for an entire long weekend and data lost.

She confirmed as of today that the first data was sent by Jason, she added it, but **she confirmed the source data also has holes**. By source data, I mean in this case the data living in **Web CTRL**. This is why our **Frog_UHM** database, in turn, also has holes. TL;DR: Nothing can be done about this.

## SeconD request

and also down the comments:

> okay here is where we are missing in October and I think the data is all there in webctrl: all sensors from 2017-10-07 06:00 to 2017-10-07 08:00 and 2017-10-08 03:00 to 2017-10-08 05:00

For this second request, she said: "Jason sent something but I still didn't have time to look at it yet". As such, I am leaving this issue open as a reminder. @jygh98 I strongly recommend you **forward me** both e-mails you sent her with the same title, but clearly stating which of the two requests it resolves. I will forward it to slack in the appropriate channel. If you sent via UH File Drop, at least tell us the timestamp you did so in case she has a hard time finding later (if the link is not expired by then!).

**Comment by eileenpeppard** [comment] 2017-10-16 22:48
Jason sent me files with dhhl in label, so it was a little confusing! I let him know. i have verified it really us frog-uhm data and will upload and let you know how it looks. Thanks.

**Comment by eileenpeppard** [comment] 2017-10-17 01:12
Okay, guys, you can close the issue. it was not a problem with scrape-util. The data is missing from webctrl. For the record: on 2017-10-07 the 0705, 0710, and 0715 are missing and the 0720 is not always on the 5-minute mark. Some have a 07:19:53 and the 07:20:00, etc. Weird.  On 2017-10-08 all sensors seem to be missing the 04:00 reading.

**Comment by carlosparadis** [comment] 2017-10-17 03:09
Thank you for the heads-up. I am tagging all our problems with missing data so we can better prioritize where the issues to fix by those that keep coming back more often. I am marking this as "Won't fix" since they were both problems in the source.

**Closed by carlosparadis** 2017-10-17 03:09 UTC
Labels: prio: high, stat:next, type: missing data
